const fs=require('fs'),vm=require('vm'),crypto=require('crypto');
global.Utilities={DigestAlgorithm:{SHA_256:'SHA_256'},Charset:{UTF_8:'UTF_8'},computeDigest:(a,s)=>Array.from(crypto.createHash('sha256').update(String(s),'utf8').digest()).map(x=>x>127?x-256:x),formatDate:d=>new Date(d).toISOString().slice(0,10)};
global.Session={getActiveUser:()=>({getEmail:()=>''})};global.PropertiesService={getScriptProperties:()=>({getProperty:()=>'',setProperty:()=>{throw Error('PROPERTY_WRITE_FORBIDDEN')}})};for(const x of ['SpreadsheetApp','DriveApp','UrlFetchApp'])global[x]=new Proxy({},{get:()=>{throw Error(x+'_FORBIDDEN') }});
for(const f of fs.readdirSync(__dirname).filter(x=>x.endsWith('.js')).sort())vm.runInThisContext(fs.readFileSync(__dirname+'/'+f,'utf8'),{filename:f});
const fx=BSE_EXACT_REAL_MESSAGE_CORPUS['RM-011'],r=bseTreatmentListParseMessage_(fx.text,fx.received_at),corpus=bseExactCorpusDispatch_('RM-011',fx),c=r.candidates[0],queue=bseTelegramQueueStatus_(r);
const groups=fx.text.split(/(?=\*\d+\.\s*M\d+)/).filter(x=>/\*\d+\.\s*M\d+/.test(x)).map(x=>({heading:x.split('\n')[0],materials:x.split('\n').slice(1).map(z=>z.trim()).filter(z=>/^[A-Za-z][A-Za-z\s]+\s*-\s*\d+/.test(z))}));
const expected=[['M3P34','PERIA','Acerio - 300'],['M3P12','TIMUN','Amistartop - 200'],['','Peria','Acerio - 30'],['M4P12','Peria','Acerio - 30']];
const pass=corpus.pass&&r.production_write===false&&r.candidates.length===4&&r.validation==='NEED_INFO'&&queue==='WAITING_INFO'&&r.candidates.every((c,i)=>c.target==='Treatment_Event_Log'&&c.fields.event_status==='COMPLETED'&&c.fields.crop.toLowerCase()===expected[i][1].toLowerCase()&&c.fields.plot_ids.join('')===expected[i][0]&&c.fields.treatment_description.split('\n').length===4&&c.fields.treatment_description.includes(expected[i][2])&&c.missing.includes('active_allocation_unverified')&&(!expected[i][0]?c.missing.includes('plot_ids'):true)&&!/(\bml\b|\bmg\b|\bliter\b)/i.test(c.fields.treatment_description));
console.log(JSON.stringify({pass,hash:bseExactCorpusHash_(fx.text),validation:r.validation,route:corpus.route,candidate_count:r.candidates.length,missing:c.missing,candidate:c.fields,source_groups:groups,all_candidates:r.candidates.map(z=>({crop:z.fields.crop,plot:z.fields.plot_ids,missing:z.missing,description:z.fields.treatment_description})),queue_expected:queue,production_write:r.production_write,active_checked_by_parser:false},null,2));if(!pass)process.exitCode=2;
