/** @OnlyCurrentDoc */
// TEST-only PM plot-status retrieval. Reads approved TEST records and writes audit only.
const BSE_TG_PLOT_STATUS_AUDIT_HEADERS=['requested_at','telegram_user_id','chat_id','plot_id','outcome','reason'];

function bseTelegramPlotStatusCommand_(text){const match=String(text||'').match(/^\/status\s+plot\s+(M[1-9]\d*P[1-9]\d*)\s*$/i);return match?match[1].toUpperCase():'';}
function bseTelegramPlotStatusAudit_(book){let sheet=book.getSheetByName('TEST_TELEGRAM_PLOT_STATUS_AUDIT');if(!sheet)sheet=book.insertSheet('TEST_TELEGRAM_PLOT_STATUS_AUDIT');bseEnsureAdditiveHeaders_(sheet,BSE_TG_PLOT_STATUS_AUDIT_HEADERS);return sheet;}
function bseTelegramPlotStatusRows_(book,name,headers){return bseTransplantRowsByName_(book,name,headers);}
function bseTelegramPlotStatusLatest_(rows,dateIndex){let latest=null;rows.forEach((row,index)=>{const value=String(row[dateIndex]||''),stamp=Date.parse(value),time=Number.isFinite(stamp)?stamp:-1;if(!latest||time>latest.time||time===latest.time&&index>latest.index)latest={row:row,index:index,time:time,value:value};});return latest;}
function bseTelegramPlotStatusSummary_(book,plotId){
  const batches=bseTelegramPlotStatusRows_(book,'TEST_CROP_BATCH',BSE_CROP_BATCH_HEADERS),allocations=bseTelegramPlotStatusRows_(book,'TEST_PLOT_ALLOCATION',BSE_PLOT_ALLOCATION_HEADERS),reviews=bseTelegramPlotStatusRows_(book,'TEST_CROP_BATCH_REVIEW',BSE_CROP_BATCH_REVIEW_HEADERS),statuses=bseTelegramPlotStatusRows_(book,'TEST_ALLOCATION_STATUS_EVENT',BSE_ALLOCATION_STATUS_EVENT_HEADERS);
  const approved=new Set(reviews.filter(row=>String(row[3])==='Crop_Batch_Log'&&String(row[5])==='APPROVED').map(row=>String(row[11]))),effective=bseActiveAllocationEffectiveStatuses_(statuses),matches=[];
  allocations.forEach(row=>{const batchId=String(row[2]||''),allocationId=String(row[3]||''),batch=batches.find(item=>String(item[2])===batchId),state=effective[allocationId];if(String(row[5])===plotId&&String(row[6])==='PLANNED'&&approved.has(batchId)&&batch&&state&&state.status==='ACTIVE')matches.push({batch:batch,allocation:row,state:state});});
  if(!matches.length)return {kind:'NONE'};
  if(matches.length!==1)return {kind:'MULTIPLE'};
  const match=matches[0],allocationId=String(match.allocation[3]),censuses=bseTelegramPlotStatusRows_(book,'TEST_PLANT_CENSUS',BSE_PLANT_CENSUS_HEADERS).filter(row=>String(row[4])===allocationId&&String(row[5])===plotId&&String(row[9])==='VERIFIED_TEST'),links=bseTelegramPlotStatusRows_(book,'TEST_TREATMENT_ALLOCATION_LINK',BSE_TREATMENT_ALLOCATION_LINK_HEADERS).filter(row=>String(row[4])===allocationId&&String(row[5])===plotId),events=bseTelegramPlotStatusRows_(book,'TEST_TREATMENT_EVENT',BSE_TREATMENT_EVENT_HEADERS);
  const census=bseTelegramPlotStatusLatest_(censuses,6),eventIds=new Set(links.map(row=>String(row[2]))),treatment=bseTelegramPlotStatusLatest_(events.filter(row=>eventIds.has(String(row[2]))&&String(row[8])==='COMPLETED'&&String(row[9])==='VERIFIED_TEST'),4);
  return {kind:'UNIQUE',batch_id:String(match.batch[2]),crop:String(match.batch[4]),allocation_status:String(match.state.status),census:census&&{date:String(census.row[6]),count:String(census.row[8])},treatment:treatment&&{date:String(treatment.row[4]),description:String(treatment.row[6])}};
}
function bseTelegramPlotStatusText_(plotId,summary){if(summary.kind==='NONE')return 'Status Plot TEST '+plotId+'\nTiada allocation ACTIVE TEST yang diluluskan.\nMod TEST — tiada rekod production ditulis.';if(summary.kind==='MULTIPLE')return 'Status Plot TEST '+plotId+' tidak dapat dirumuskan kerana terdapat lebih daripada satu allocation ACTIVE TEST. Hubungi owner/admin.\nMod TEST — tiada rekod production ditulis.';return ['Status Plot TEST '+plotId,'Tanaman: '+summary.crop,'Batch: '+summary.batch_id,'Status allocation: '+summary.allocation_status,'Banci terakhir: '+(summary.census?summary.census.date+' — '+summary.census.count+' pokok':'tiada rekod disahkan'),'Rawatan terakhir: '+(summary.treatment?summary.treatment.date+' — '+summary.treatment.description:'tiada rekod disahkan'),'Mod TEST — tiada rekod production ditulis.'].join('\n');}
function bseTelegramPlotStatusRetrieve_(book,message){const plotId=bseTelegramPlotStatusCommand_(message&&message.text);if(!plotId)return {handled:false};const user=String(message&&message.from&&message.from.id||''),chat=String(message&&message.chat&&message.chat.id||''),audit=(outcome,reason)=>{bseTelegramPlotStatusAudit_(book).appendRow([new Date().toISOString(),user,chat,plotId,outcome,reason]);SpreadsheetApp.flush();};const access=bseTelegramRegistrationPrivateAccess_(book,message);if(access.status==='NOT_PRIVATE'){audit('DENIED','NOT_PRIVATE');return {handled:true,text:'Status plot hanya boleh diminta melalui PM bot.'};}if(!['REGISTERED_ACTIVE','OWNER_ACTIVE'].includes(access.status)){audit('DENIED','NOT_REGISTERED_ACTIVE');return {handled:true,text:'Status plot hanya untuk ahli aktif melalui PM bot.'};}const summary=bseTelegramPlotStatusSummary_(book,plotId),outcome=summary.kind==='UNIQUE'?'SENT':summary.kind==='NONE'?'NOT_FOUND':'AMBIGUOUS';audit(outcome,summary.kind);return {handled:true,text:bseTelegramPlotStatusText_(plotId,summary),production_write:false};}

function runBseTelegramPlotStatusHarnessTests(){const parser=bseTelegramPlotStatusCommand_.toString(),handler=bseTelegramPlotStatusRetrieve_.toString(),summary=bseTelegramPlotStatusSummary_.toString(),tests=[{id:'accepts one exact canonical plot command',pass:bseTelegramPlotStatusCommand_('/status plot M2P1')==='M2P1'},{id:'rejects extra command content',pass:bseTelegramPlotStatusCommand_('/status plot M2P1 extra')===''}, {id:'parser is anchored and canonical',pass:/\^\\\/status/.test(parser)&&/M\[1-9\]/.test(parser)&&/\\s\*\$/.test(parser)}, {id:'requires registered private access',pass:/bseTelegramRegistrationPrivateAccess_/.test(handler)&&/NOT_PRIVATE/.test(handler)&&/REGISTERED_ACTIVE/.test(handler)}, {id:'reads TEST records and handles ambiguity',pass:/TEST_CROP_BATCH|TEST_PLANT_CENSUS|TEST_TREATMENT_EVENT/.test(summary)&&/MULTIPLE/.test(summary)}, {id:'no domain or production writer',pass:!/production_write\s*:\s*true|bseCropBatchAppend_|setValue\(/.test([handler,summary].join('\n'))}];const failed=tests.filter(test=>!test.pass);console.log('PLOT_STATUS_RETRIEVAL_HARNESS: '+JSON.stringify(tests));if(failed.length)throw new Error('Plot status retrieval harness gagal: '+failed.map(test=>test.id).join(', '));return tests;}
