/** @OnlyCurrentDoc */
// TEST-only owner/admin PM history. It reads canonical confirmed records only.
const BSE_TG_HISTORY_AUDIT_HEADERS=['requested_at','telegram_user_id','private_chat_id','period','outcome','reason','matched_count','displayed_count'];
const BSE_TG_HISTORY_MAX_MATCHES=100;
const BSE_TG_HISTORY_MAX_DISPLAY=20;
function bseTelegramHistoryAudit_(book){let s=book.getSheetByName('TEST_TELEGRAM_HISTORY_AUDIT');if(!s)s=book.insertSheet('TEST_TELEGRAM_HISTORY_AUDIT');bseEnsureAdditiveHeaders_(s,BSE_TG_HISTORY_AUDIT_HEADERS);return s;}
function bseTelegramHistoryCommand_(text){const raw=String(text||'').trim();if(!/^\/history\b/i.test(raw))return null;const m=raw.match(/^\/history\s+(\d{4}-(?:\d{2})(?:-\d{2})?)\s*$/i);if(!m)return {invalid:true};const key=m[1],parts=key.split('-').map(Number),month=parts[1],day=parts[2];if(month<1||month>12||(day!==undefined&&(day<1||day>31)))return {invalid:true};if(day!==undefined){const probe=new Date(Date.UTC(parts[0],month-1,day));if(probe.getUTCFullYear()!==parts[0]||probe.getUTCMonth()!==month-1||probe.getUTCDate()!==day)return {invalid:true};}return {period:key,kind:day===undefined?'MONTH':'DAY'};}
function bseTelegramHistoryDate_(value){if(Object.prototype.toString.call(value)==='[object Date]'&&!isNaN(value.getTime()))return Utilities.formatDate(value,'Asia/Kuala_Lumpur','yyyy-MM-dd');const raw=String(value||'').trim(),match=raw.match(/^(\d{4}-\d{2}-\d{2})/);if(match)return match[1];const parsed=new Date(raw);return isNaN(parsed.getTime())?'':Utilities.formatDate(parsed,'Asia/Kuala_Lumpur','yyyy-MM-dd');}
function bseTelegramHistoryInPeriod_(date,period){return String(date||'')===String(period)||String(date||'').indexOf(String(period)+'-')===0;}
function bseTelegramHistorySafeLine_(event){return [event.date,event.reference,event.category,event.summary].map(v=>String(v||'').replace(/[\r\n]+/g,' ').replace(/\s+/g,' ').trim()).join(' | ').slice(0,220);}
function bseTelegramHistoryRecordEvents_(book){const queueRows=bseTelegramRecordReadRows_(book,'TELEGRAM_TEST_QUEUE',BSE_TG_QUEUE_HEADERS.length),approvalRows=bseTelegramRecordReadRows_(book,'TEST_TELEGRAM_APPROVAL_UI',BSE_APPROVAL_UI_HEADERS.length),events=[];approvalRows.filter(row=>String(row[17])==='REPORTER_CONFIRMED').forEach(approval=>{const reference=String(approval[0]||''),matches=queueRows.filter(row=>'BSE-TG-'+String(row[0])===reference&&String(row[6])!=='VOIDED_TEST');if(matches.length!==1)return;const queue=matches[0];let result;try{result=JSON.parse(String(queue[9]||''));}catch(_){return;}if(!result||result.production_write!==false||result.validation!=='PASS'||bseApprovalHash_(result)!==String(approval[2]||''))return;let meta={};try{meta=JSON.parse(String(queue[16]||'{}'));}catch(_){}const candidates=(result.candidates||[]).map(bseTelegramRecordSafeCandidateLine_).filter(Boolean);events.push({date:bseTelegramHistoryDate_(approval[15]||queue[17]||queue[5]),reference:reference,category:bseTelegramRecordCandidateCategory_(result,String(meta.source_chat_type||'')==='private'),summary:candidates.join(' / ').slice(0,160)});});return events;}
function bseTelegramHistoryEvidenceEvents_(book){const sheet=book.getSheetByName('TEST_FILE_EVIDENCE');if(!sheet)return [];return bseTelegramRecordReadRows_(book,'TEST_FILE_EVIDENCE',BSE_TG_EVIDENCE_HEADERS.length).filter(row=>String(row[16])==='CONFIRMED_TEST').map(row=>({date:bseTelegramHistoryDate_(row[20]||row[6]),reference:String(row[0]||''),category:String(row[14]||'UNCLASSIFIED_TEST'),summary:'Evidence '+String(row[8]||'UNKNOWN')}));}
function bseTelegramHistoryRetrieve_(book,m){const command=bseTelegramHistoryCommand_(m&&m.text);if(!command)return {handled:false};const user=String(m&&m.from&&m.from.id||''),chat=String(m&&m.chat&&m.chat.id||''),period=command.period||'',audit=(outcome,reason,matched,displayed)=>{bseTelegramHistoryAudit_(book).appendRow([new Date().toISOString(),user,chat,period,outcome,reason,Number(matched||0),Number(displayed||0)]);SpreadsheetApp.flush();};if(command.invalid){audit('DENIED','INVALID_PERIOD',0,0);return {handled:true,text:'Format: /history YYYY-MM-DD atau /history YYYY-MM'};}const owner=bseTestOwnerForTelegramUser_(book,user);if(!m||!m.chat||m.chat.type!=='private'||!owner.ok||String(owner.private_chat_id)!==chat){audit('DENIED',m&&m.chat&&m.chat.type!=='private'?'NOT_PRIVATE':'NOT_OWNER_ACTIVE',0,0);return {handled:true,text:'History hanya boleh diminta oleh owner/admin aktif melalui PM bot.'};}const all=bseTelegramHistoryRecordEvents_(book).concat(bseTelegramHistoryEvidenceEvents_(book)).filter(event=>bseTelegramHistoryInPeriod_(event.date,command.period)).sort((a,b)=>String(a.date).localeCompare(String(b.date))||String(a.reference).localeCompare(String(b.reference))).slice(0,BSE_TG_HISTORY_MAX_MATCHES),displayed=all.slice(0,BSE_TG_HISTORY_MAX_DISPLAY),lines=['Sejarah TEST — '+command.period];if(!displayed.length)lines.push('Tiada rekod TEST yang telah disahkan dalam sela masa ini.');else displayed.forEach(event=>lines.push(bseTelegramHistorySafeLine_(event)));if(all.length>displayed.length)lines.push('Dipaparkan '+displayed.length+' daripada '+all.length+' rekod yang dipadankan.');lines.push('Mod TEST — tiada rekod production ditulis.');audit('SENT','OWNER_ACTIVE',all.length,displayed.length);return {handled:true,text:lines.join('\n')};}
function runBseTelegramHistoryHarnessTests(){const day=bseTelegramHistoryCommand_('/history 2026-09-21'),month=bseTelegramHistoryCommand_('/history 2026-09'),source=bseTelegramHistoryRetrieve_.toString()+bseTelegramHistoryRecordEvents_.toString()+bseTelegramHistoryEvidenceEvents_.toString(),tests=[{id:'only exact day or month command accepted',pass:day.period==='2026-09-21'&&month.kind==='MONTH'&&bseTelegramHistoryCommand_('/history 2026-02-30').invalid===true&&bseTelegramHistoryCommand_('/history Jun').invalid===true},{id:'period matching is exact',pass:bseTelegramHistoryInPeriod_('2026-09-21','2026-09')&&bseTelegramHistoryInPeriod_('2026-09-21','2026-09-21')&&!bseTelegramHistoryInPeriod_('2026-09-22','2026-09-21')},{id:'PM owner access is mandatory',pass:/owner\.ok/.test(source)&&/private_chat_id/.test(source)&&/NOT_OWNER_ACTIVE/.test(source)},{id:'only confirmed and integrity-checked records are read',pass:/REPORTER_CONFIRMED/.test(source)&&/bseApprovalHash_/.test(source)&&/VOIDED_TEST/.test(source)&&/CONFIRMED_TEST/.test(source)},{id:'response excludes original text and payload',pass:!/original_note|candidate_json|caption/.test(bseTelegramHistorySafeLine_.toString()+bseTelegramHistoryRetrieve_.toString())},{id:'no domain or production writer',pass:!/bse(?:Measurement|CropBatch|Transplant|PlantCensus|Treatment|Inventory)ReviewCore_|production_write\s*:\s*true/.test(source)}];console.log('TELEGRAM_HISTORY_HARNESS: '+JSON.stringify(tests));const failures=tests.filter(t=>!t.pass);if(failures.length)throw new Error('Telegram history harness gagal: '+failures.map(t=>t.id).join(', '));return tests;}
