/** @OnlyCurrentDoc */
// TEST-only PM retrieval for reporter-confirmed Telegram records.  No domain writer.
const BSE_TG_RECORD_RETRIEVAL_AUDIT_HEADERS=['requested_at','telegram_user_id','private_chat_id','reference','outcome','reason'];
function bseTelegramRecordRetrievalAudit_(book){let s=book.getSheetByName('TEST_TELEGRAM_RECORD_RETRIEVAL_AUDIT');if(!s)s=book.insertSheet('TEST_TELEGRAM_RECORD_RETRIEVAL_AUDIT');bseEnsureAdditiveHeaders_(s,BSE_TG_RECORD_RETRIEVAL_AUDIT_HEADERS);return s;}
function bseTelegramRecordRetrieveCommand_(text){const m=String(text||'').match(/^\/retrieve\s+(BSE-TG-\d+)\s*$/i);return m?m[1].toUpperCase():'';}
function bseTelegramRecordReadRows_(book,name,width){const s=book.getSheetByName(name);return s&&s.getLastRow()>1?s.getRange(2,1,s.getLastRow()-1,width).getValues():[];}
function bseTelegramRecordCandidateCategory_(result,privateSource){if(privateSource)return 'PRIVATE_SUBMISSION';const targets=(result&&result.candidates||[]).map(c=>String(c&&c.target||''));if(!targets.length)return 'UNCLASSIFIED_TEST';if(targets.every(t=>['Crop_Batch_Log','Planting_Event_Log','Plot_Allocation_Log','Transplant_Event_Log','Plant_Census_Log','Treatment_Event_Log','Measurement_Log'].includes(t)))return 'FIELD_OPERATION';if(targets.length===1&&targets[0]==='Asset_Proposal_Log')return 'ASSET_EQUIPMENT';if(targets.length===1&&['Inventory_Event_Log','Input_Usage_Log','Claim_Request_Log'].includes(targets[0]))return 'INVENTORY_CLAIM';return 'UNCLASSIFIED_TEST';}
function bseTelegramRecordSafeCandidateLine_(candidate){const c=candidate||{},f=c.fields||{},target=String(c.target||'');const values=[];if(target==='Crop_Batch_Log'){values.push(f.crop,f.variety,f.event_date);}
else if(target==='Planting_Event_Log'||target==='Plot_Allocation_Log'||target==='Transplant_Event_Log'||target==='Plant_Census_Log'||target==='Treatment_Event_Log'||target==='Measurement_Log'){values.push(f.crop,f.event_date,f.plot_id,f.plot_ids,f.measurement_type,f.value,f.unit,f.treatment_description);}
else if(target==='Asset_Proposal_Log'){values.push(f.asset_name,f.quantity,f.unit);}
else if(target==='Inventory_Event_Log'||target==='Input_Usage_Log'||target==='Claim_Request_Log'){values.push(f.item_name,f.quantity,f.unit,f.amount_myr,f.plot_id);}
return target+(values.filter(v=>v||v===0).length?' | '+values.filter(v=>v||v===0).map(v=>String(v).replace(/[\r\n]+/g,' ').trim()).join(' '):'');}
function bseTelegramRecordRetrieve_(book,m){const ref=bseTelegramRecordRetrieveCommand_(m&&m.text);if(!ref)return {handled:false};const user=String(m&&m.from&&m.from.id||''),chat=String(m&&m.chat&&m.chat.id||''),audit=(outcome,reason)=>{bseTelegramRecordRetrievalAudit_(book).appendRow([new Date().toISOString(),user,chat,ref,outcome,reason]);SpreadsheetApp.flush();};const access=bseTelegramRegistrationPrivateAccess_(book,m);if(!['REGISTERED_ACTIVE','OWNER_ACTIVE'].includes(access.status)){audit('DENIED',access.status==='NOT_PRIVATE'?'NOT_PRIVATE':'NOT_REGISTERED_ACTIVE');return {handled:true,text:access.status==='NOT_PRIVATE'?'Retrieval rekod hanya boleh diminta melalui PM bot.':'Retrieval hanya untuk ahli aktif melalui PM bot.'};}
const queueRows=bseTelegramRecordReadRows_(book,'TELEGRAM_TEST_QUEUE',BSE_TG_QUEUE_HEADERS.length),approvalRows=bseTelegramRecordReadRows_(book,'TEST_TELEGRAM_APPROVAL_UI',BSE_APPROVAL_UI_HEADERS.length),queueMatches=queueRows.filter(r=>('BSE-TG-'+String(r[0]))===ref),approvalMatches=approvalRows.filter(r=>String(r[0])===ref&&String(r[17])==='REPORTER_CONFIRMED');if(queueMatches.length!==1||approvalMatches.length!==1){audit('DENIED','NOT_CONFIRMED_OR_AMBIGUOUS');return {handled:true,text:'Rujukan rekod TEST tidak ditemui atau belum disahkan.'};}
const queue=queueMatches[0],approval=approvalMatches[0];let result;try{result=JSON.parse(String(queue[9]||''));}catch(_){audit('DENIED','CANDIDATE_JSON_INVALID');return {handled:true,text:'Rekod TEST ini tidak boleh diambil dengan selamat.'};}if(result.production_write!==false||result.validation!=='PASS'||bseApprovalHash_(result)!==String(approval[2]||'')){audit('DENIED','PAYLOAD_INTEGRITY');return {handled:true,text:'Rekod TEST ini tidak boleh diambil dengan selamat.'};}
let meta={};try{meta=JSON.parse(String(queue[16]||'{}'));}catch(_){}const category=bseTelegramRecordCandidateCategory_(result,String(meta.source_chat_type||'')==='private'),owner=bseTestOwnerForTelegramUser_(book,user).ok,reporter=String(queue[2])===user,standard=category==='FIELD_OPERATION'||category==='ASSET_EQUIPMENT';if(!(owner||reporter||standard)){audit('DENIED','VISIBILITY_DENIED_'+category);return {handled:true,text:'Anda tidak mempunyai akses kepada rekod ini.'};}
const lines=['Rekod TEST '+ref,'Kategori: '+category,'Status: REPORTER_CONFIRMED'];(result.candidates||[]).forEach(c=>lines.push(bseTelegramRecordSafeCandidateLine_(c)));lines.push('Mod TEST — tiada rekod production ditulis.');audit('SENT',owner?'OWNER_ACTIVE':reporter?'ORIGINAL_REPORTER':category);return {handled:true,text:lines.join('\n')};}
function runBseTelegramRecordRetrievalHarnessTests(){const field={production_write:false,validation:'PASS',candidates:[{target:'Plant_Census_Log',fields:{crop:'Timun',event_date:'2026-09-22',plot_ids:'M2P1',value:96,unit:'pokok'}}]},claim={production_write:false,validation:'PASS',candidates:[{target:'Claim_Request_Log',fields:{item_name:'Sarung tangan',amount_myr:50}}]},source=bseTelegramRecordRetrieve_.toString()+bseTelegramRecordCandidateCategory_.toString()+bseTelegramRecordSafeCandidateLine_.toString(),tests=[{id:'exact BSE-TG command only',pass:bseTelegramRecordRetrieveCommand_('/retrieve BSE-TG-123')==='BSE-TG-123'&&!bseTelegramRecordRetrieveCommand_('/retrieve BSE-TG-ABC')&&!bseTelegramRecordRetrieveCommand_('/retrieve BSE-TG-123 more')},{id:'category is explicit and private overrides',pass:bseTelegramRecordCandidateCategory_(field,false)==='FIELD_OPERATION'&&bseTelegramRecordCandidateCategory_(claim,false)==='INVENTORY_CLAIM'&&bseTelegramRecordCandidateCategory_(field,true)==='PRIVATE_SUBMISSION'},{id:'summary has controlled fields only',pass:bseTelegramRecordSafeCandidateLine_(field.candidates[0])==='Plant_Census_Log | Timun 2026-09-22 M2P1 96 pokok'&&!/original_note/.test(source)},{id:'confirmed hash and PM access are mandatory',pass:/REPORTER_CONFIRMED/.test(source)&&/bseApprovalHash_/.test(source)&&/bseTelegramRegistrationPrivateAccess_/.test(source)},{id:'default deny protects restricted categories',pass:/owner\|\|reporter\|\|standard/.test(source)&&/VISIBILITY_DENIED/.test(source)},{id:'no domain or production writer',pass:!/bse(?:Measurement|CropBatch|Transplant|PlantCensus|Treatment|Inventory)ReviewCore_|production_write\s*:\s*true/.test(source)}];console.log('TELEGRAM_RECORD_RETRIEVAL_HARNESS: '+JSON.stringify(tests));const failures=tests.filter(t=>!t.pass);if(failures.length)throw new Error('Record retrieval harness gagal: '+failures.map(t=>t.id).join(', '));return tests;}
