/** @OnlyCurrentDoc */
// TEST-only review for explicit completed treatment. No inventory, claims, production writes, or allocation mutation.
const BSE_TREATMENT_EVENT_HEADERS=['source_key','queue_update_id','treatment_event_id','batch_id','event_date','crop','treatment_description','plot_ids_json','event_status','verification_status','original_note','approved_at','reviewer','payload_hash'];
const BSE_TREATMENT_ALLOCATION_LINK_HEADERS=['source_key','queue_update_id','treatment_event_id','batch_id','allocation_id','plot_id','event_date','payload_hash'];
const BSE_TREATMENT_REVIEW_HEADERS=['review_id','source_key','queue_update_id','target','payload_hash','decision','reviewer','review_note','reviewed_at','queue_status_before','candidate_json','treatment_event_id','batch_id'];

function approveTelegramTreatmentByReference(){const reference=bsePromptTreatmentReference_('Lulus Rawatan TEST');if(reference)return bseReviewTelegramTreatmentByReference_('APPROVED',reference,'');}
function rejectTelegramTreatmentByReference(){const reference=bsePromptTreatmentReference_('Tolak Rawatan TEST');if(!reference)return;const ui=SpreadsheetApp.getUi(),response=ui.prompt('Tolak Rawatan TEST','Nyatakan sebab penolakan:',ui.ButtonSet.OK_CANCEL);if(response.getSelectedButton()!==ui.Button.OK)return;const note=response.getResponseText().trim();if(!note)throw new Error('Sebab penolakan wajib diisi.');return bseReviewTelegramTreatmentByReference_('REJECTED',reference,note);}
function bsePromptTreatmentReference_(title){const ui=SpreadsheetApp.getUi(),response=ui.prompt(title,'Masukkan rujukan tepat, contohnya BSE-TG-123456:',ui.ButtonSet.OK_CANCEL);if(response.getSelectedButton()!==ui.Button.OK)return '';const reference=response.getResponseText().trim();if(!/^BSE-TG-\d+$/.test(reference))throw new Error('Rujukan mesti tepat dalam format BSE-TG-<update_id>.');return reference;}

function bseReviewTelegramTreatmentByReference_(decision,reference,note){
  bseTreatmentRequireDecision_(decision,note);if(!/^BSE-TG-\d+$/.test(reference))throw new Error('Rujukan mesti tepat dalam format BSE-TG-<update_id>.');const lock=LockService.getScriptLock();if(!lock.tryLock(10000))throw new Error('Barisan sedang dikemas kini. Cuba semula.');
  try{
    const book=boundTestBook_(),queue=bseTelegramQueue_(book),rows=bseCropBatchRows_(queue,BSE_TG_QUEUE_HEADERS.length),updateId=reference.slice(7),matches=rows.map((row,index)=>({row:row,sheetRow:index+2})).filter(item=>String(item.row[0])===updateId);
    if(matches.length!==1)throw new Error('Rujukan mesti sepadan dengan tepat satu baris TELEGRAM_TEST_QUEUE.');const selected=matches[0],status=String(selected.row[6]||''),root=bseCropBatchRoot_(rows,selected.row),proposal=bseTreatmentProposal_(selected.row[9],root.provenance),sourceKey='BSE-TG-'+root.updateId+'|Treatment_Event_Log',payloadHash=bseCropBatchHash_(proposal.canonical),expectedStatus=decision==='APPROVED'?'TREATMENT_APPROVED_TEST':'TREATMENT_REJECTED_TEST';
    const reviewSheet=book.getSheetByName('TEST_TREATMENT_REVIEW')?bseCropBatchSheet_(book,'TEST_TREATMENT_REVIEW',BSE_TREATMENT_REVIEW_HEADERS):null,eventSheet=book.getSheetByName('TEST_TREATMENT_EVENT')?bseCropBatchSheet_(book,'TEST_TREATMENT_EVENT',BSE_TREATMENT_EVENT_HEADERS):null,linkSheet=book.getSheetByName('TEST_TREATMENT_ALLOCATION_LINK')?bseCropBatchSheet_(book,'TEST_TREATMENT_ALLOCATION_LINK',BSE_TREATMENT_ALLOCATION_LINK_HEADERS):null,reviews=reviewSheet?bseCropBatchRows_(reviewSheet,BSE_TREATMENT_REVIEW_HEADERS.length):[],events=eventSheet?bseCropBatchRows_(eventSheet,BSE_TREATMENT_EVENT_HEADERS.length):[],links=linkSheet?bseCropBatchRows_(linkSheet,BSE_TREATMENT_ALLOCATION_LINK_HEADERS.length):[];
    const prior=reviews.find(row=>String(row[1])===sourceKey);
    if(prior){if(String(prior[4])!==payloadHash||String(prior[5])!==decision)throw new Error('Konflik semakan sedia ada untuk source_key ini.');const eventId=String(prior[11]||''),batchId=String(prior[12]||'');if(decision==='APPROVED')bseTreatmentAssertApprovedRows_(events,links,sourceKey,payloadHash,proposal.plots,eventId,batchId);else if(events.some(row=>String(row[0])===sourceKey)||links.some(row=>String(row[0])===sourceKey))throw new Error('Audit REJECTED bercanggah dengan rekod Rawatan TEST.');if(status===expectedStatus)return {source_key:sourceKey,decision:decision,duplicate:true,production_write:false};if(status!=='NEEDS_HUMAN_REVIEW')throw new Error('Status queue tidak konsisten dengan audit Rawatan sedia ada.');queue.getRange(selected.sheetRow,7).setValue(expectedStatus);SpreadsheetApp.flush();return {source_key:sourceKey,decision:decision,duplicate:true,production_write:false};}
    if(status!=='NEEDS_HUMAN_REVIEW')throw new Error('Baris queue bukan NEEDS_HUMAN_REVIEW.');if(events.some(row=>String(row[0])===sourceKey)||links.some(row=>String(row[0])===sourceKey))throw new Error('Konflik rekod Rawatan TEST sedia ada.');const match=bseTreatmentMatchForBook_(book,proposal);if(decision==='APPROVED'&&match.kind!=='UNIQUE')throw new Error('Batch Crop Batch atau allocation ACTIVE tidak sepadan; tiada write dibuat.');
    const reviewer=bseCropBatchReviewer_(),stamp=new Date().toISOString(),reviewOut=reviewSheet||bseCropBatchSheet_(book,'TEST_TREATMENT_REVIEW',BSE_TREATMENT_REVIEW_HEADERS);let eventId='',batchId='';
    if(decision==='APPROVED'){const eventOut=eventSheet||bseCropBatchSheet_(book,'TEST_TREATMENT_EVENT',BSE_TREATMENT_EVENT_HEADERS),linkOut=linkSheet||bseCropBatchSheet_(book,'TEST_TREATMENT_ALLOCATION_LINK',BSE_TREATMENT_ALLOCATION_LINK_HEADERS);eventId=bseTreatmentNextId_(events,proposal.fields.event_date);batchId=match.batch_id;bseCropBatchAppend_(eventOut,[sourceKey,root.updateId,eventId,batchId,proposal.fields.event_date,proposal.fields.crop,proposal.fields.treatment_description,JSON.stringify(proposal.plots),'COMPLETED','VERIFIED_TEST',root.provenance,stamp,reviewer,payloadHash]);match.allocations.forEach(allocation=>bseCropBatchAppend_(linkOut,[sourceKey,root.updateId,eventId,batchId,allocation.allocation_id,allocation.plot_id,proposal.fields.event_date,payloadHash]));SpreadsheetApp.flush();}
    bseCropBatchAppend_(reviewOut,[Utilities.getUuid(),sourceKey,root.updateId,'Treatment_Event_Log',payloadHash,decision,reviewer,String(note||'').trim(),stamp,status,JSON.stringify(proposal.canonical),eventId,batchId]);SpreadsheetApp.flush();queue.getRange(selected.sheetRow,7).setValue(expectedStatus);SpreadsheetApp.flush();return {source_key:sourceKey,decision:decision,duplicate:false,production_write:false};
  }finally{lock.releaseLock();}
}
function bseTreatmentRequireDecision_(decision,note){if(!['APPROVED','REJECTED'].includes(decision))throw new Error('Keputusan semakan tidak sah.');if(decision==='REJECTED'&&!String(note||'').trim())throw new Error('Sebab penolakan wajib diisi.');}
function bseTreatmentProposal_(encoded,original){let result;try{result=JSON.parse(String(encoded||''));}catch(_){throw new Error('candidate_json tidak sah.');}if(!result||typeof result!=='object'||Array.isArray(result)||Object.keys(result).some(key=>!['validation','production_write','candidates'].includes(key))||result.validation!=='PASS'||result.production_write!==false||!Array.isArray(result.candidates)||result.candidates.length!==1)throw new Error('Hasil Rawatan TEST tidak sah.');const candidate=result.candidates[0],f=candidate&&candidate.fields,allowed=['project_id','system_year','event_date','record_type','verification_status','original_note','crop','treatment_description','plot_ids','event_status'];if(!candidate||candidate.target!=='Treatment_Event_Log'||candidate.validation!=='PASS'||!Array.isArray(candidate.missing)||candidate.missing.length||!f||typeof f!=='object'||Array.isArray(f)||Object.keys(f).some(key=>!allowed.includes(key))||f.project_id!=='BSE_SB'||f.system_year!==2026||f.record_type!=='TREATMENT_EVENT'||f.verification_status!=='PROVISIONAL'||f.original_note!==original||typeof f.crop!=='string'||!f.crop.trim()||typeof f.treatment_description!=='string'||!f.treatment_description.trim()||f.event_status!=='PROPOSED'||!bseCropBatchDate_(f.event_date)||!Array.isArray(f.plot_ids)||!f.plot_ids.length)throw new Error('Calon Rawatan gagal semakan kontrak TEST.');const plots=f.plot_ids.slice().map(String).sort(bseCropBatchPlotCompare_);if(new Set(plots).size!==plots.length||plots.some(plot=>!/^M[1-9]\d*P[1-9]\d*$/.test(plot))||JSON.stringify(plots)!==JSON.stringify(f.plot_ids))throw new Error('Plot Rawatan mesti unik dan diisih secara kanonik.');const canonical={event_date:f.event_date,crop:f.crop,treatment_description:f.treatment_description,plot_ids:plots,event_status:'PROPOSED',verification_status:'PROVISIONAL',original_note:original,production_write:false};return {fields:f,plots:plots,canonical:canonical};}
function bseTreatmentMatchForBook_(book,proposal){return bseActiveAllocationFindMatches_(proposal.fields.crop,proposal.plots,bseTransplantRowsByName_(book,'TEST_CROP_BATCH',BSE_CROP_BATCH_HEADERS),bseTransplantRowsByName_(book,'TEST_PLOT_ALLOCATION',BSE_PLOT_ALLOCATION_HEADERS),bseTransplantRowsByName_(book,'TEST_CROP_BATCH_REVIEW',BSE_CROP_BATCH_REVIEW_HEADERS),bseTransplantRowsByName_(book,'TEST_ALLOCATION_STATUS_EVENT',BSE_ALLOCATION_STATUS_EVENT_HEADERS));}
function bseTreatmentQueueGuard_(book,result){if(!result||!Array.isArray(result.candidates)||result.candidates.length!==1||!result.candidates[0]||result.candidates[0].target!=='Treatment_Event_Log'||result.validation!=='PASS')return result;let proposal;try{proposal=bseTreatmentProposal_(JSON.stringify(result),String(result.candidates[0].fields.original_note||''));}catch(_){return bseTreatmentMarkNeedInfo_(result);}return bseTreatmentMatchForBook_(book,proposal).kind==='UNIQUE'?result:bseTreatmentMarkNeedInfo_(result);}
function bseTreatmentMarkNeedInfo_(result){result.validation='NEED_INFO';result.candidates.forEach(candidate=>{if(!candidate)return;candidate.validation='NEED_INFO';candidate.missing=Array.from(new Set((Array.isArray(candidate.missing)?candidate.missing:[]).concat(['batch_match'])));});return result;}
function bseTreatmentNextId_(rows,date){if(!bseCropBatchDate_(date))throw new Error('Tarikh Rawatan tidak sah untuk ID.');const prefix='BSE-SB-TX-'+date.replace(/-/g,'')+'-',used=rows.map(row=>String(row[2]||''));let highest=0;used.forEach(id=>{const match=id.match(new RegExp('^'+prefix+'(\\d{3})$'));if(match)highest=Math.max(highest,Number(match[1]));});if(highest>=999)throw new Error('Siri Rawatan harian telah penuh.');return prefix+String(highest+1).padStart(3,'0');}
function bseTreatmentAssertApprovedRows_(events,links,sourceKey,payloadHash,plots,eventId,batchId){const event=events.filter(row=>String(row[0])===sourceKey),rows=links.filter(row=>String(row[0])===sourceKey);if(!eventId||!batchId||event.length!==1||rows.length!==plots.length||String(event[0][2])!==eventId||String(event[0][3])!==batchId||String(event[0][8])!=='COMPLETED'||String(event[0][9])!=='VERIFIED_TEST'||String(event[0][13])!==payloadHash||rows.some(row=>String(row[2])!==eventId||String(row[3])!==batchId||String(row[7])!==payloadHash)||rows.map(row=>String(row[5])).join('|')!==plots.join('|'))throw new Error('Audit APPROVED tidak sepadan dengan rekod Rawatan TEST.');}
function runBseTreatmentReviewHarnessTests(){
  const note='RAWATAN DIBUAT\nJenis Tanaman: Timun\nM2P1\nRawatan: Semburan foliar';
  const candidate={validation:'PASS',production_write:false,candidates:[{target:'Treatment_Event_Log',validation:'PASS',missing:[],fields:{project_id:'BSE_SB',system_year:2026,event_date:'2026-09-22',record_type:'TREATMENT_EVENT',verification_status:'PROVISIONAL',original_note:note,crop:'Timun',treatment_description:'Semburan foliar',plot_ids:['M2P1'],event_status:'PROPOSED'}}]};
  const proposal=bseTreatmentProposal_(JSON.stringify(bseUnifiedGuard_(candidate,{received_at:'2026-09-22T00:00:00.000Z'})),note),batch=['k','1','BSE-SB-CB-20260922-001','2026-09-22','Timun'],allocations=[['k','1',batch[2],batch[2]+'-PA-001','','M2P1','PLANNED']],reviews=[['r','k','1','Crop_Batch_Log','h','APPROVED','','','','','','BSE-SB-CB-20260922-001']],active=[['','','','',batch[2],allocations[0][3],'M2P1','PLANNED','ACTIVE','2026-09-22T01:00:00.000Z']],tests=[];
  const pass=(id,fn)=>{try{fn();tests.push({id:id,pass:true});}catch(error){tests.push({id:id,pass:false,error:error.message});}};
  pass('ACTIVE single and multi plot PASS',()=>{const plots=['M2P1','M2P2'],alloc2=allocations.concat([['k','1',batch[2],batch[2]+'-PA-002','','M2P2','PLANNED']]),active2=active.concat([['','','','',batch[2],batch[2]+'-PA-002','M2P2','PLANNED','ACTIVE','2026-09-22T01:00:00.000Z']]);if(bseActiveAllocationFindMatches_(proposal.fields.crop,proposal.plots,[batch],allocations,reviews,active).kind!=='UNIQUE'||bseActiveAllocationFindMatches_(proposal.fields.crop,plots,[batch],alloc2,reviews,active2).kind!=='UNIQUE')throw new Error('ACTIVE match gagal');});
  pass('PLANNED none multiple crop mismatch need info',()=>{const planned=bseActiveAllocationFindMatches_(proposal.fields.crop,proposal.plots,[batch],allocations,reviews,[]).kind,none=bseActiveAllocationFindMatches_(proposal.fields.crop,proposal.plots,[],allocations,reviews,active).kind,multiple=bseActiveAllocationFindMatches_(proposal.fields.crop,proposal.plots,[batch,batch.slice()],allocations,reviews,active).kind,crop=bseActiveAllocationFindMatches_('Peria',proposal.plots,[batch],allocations,reviews,active).kind,need=bseTreatmentMarkNeedInfo_(JSON.parse(JSON.stringify(candidate)));if(planned!=='NONE'||none!=='NONE'||multiple!=='MULTIPLE'||crop!=='NONE'||need.validation!=='NEED_INFO')throw new Error('guard tidak ketat');});
  pass('CADANGAN RAWATAN does not create treatment event',()=>{const suggestion={validation:'PASS',production_write:false,candidates:[{target:'Decision_Approval_Log',validation:'PASS',missing:[],fields:{project_id:'BSE_SB',system_year:2026,event_date:'2026-09-22',record_type:'DECISION_APPROVAL',verification_status:'PROVISIONAL',original_note:'CADANGAN RAWATAN\nJenis Tanaman: Timun\nM2P1\nRawatan: Semburan foliar',decision_subject:'Cadangan rawatan',proposal_text:'Cadangan sahaja',approval_status:'PROPOSED',proposed_by:'',approved_by:'',approval_date:''}}]};const guarded=bseUnifiedGuard_(suggestion,{received_at:'2026-09-22T00:00:00.000Z'});if(guarded.candidates.some(item=>item.target==='Treatment_Event_Log'))throw new Error('proposal mencipta rawatan');});
  pass('reject audit only and retry baseline unchanged',()=>{let failed=false;try{bseTreatmentRequireDecision_('REJECTED','');}catch(_){failed=true;}const eventId='BSE-SB-TX-20260922-001',events=[['sk','2',eventId,batch[2],'2026-09-22','Timun','Semburan','[\"M2P1\"]','COMPLETED','VERIFIED_TEST','','','','h']],links=[['sk','2',eventId,batch[2],allocations[0][3],'M2P1','2026-09-22','h']],before=JSON.stringify({events:events,links:links,allocations:allocations});bseTreatmentAssertApprovedRows_(events,links,'sk','h',['M2P1'],eventId,batch[2]);if(!failed||before!==JSON.stringify({events:events,links:links,allocations:allocations})||/Tasks\./.test(bseReviewTelegramTreatmentByReference_.toString()))throw new Error('audit/retry tidak selamat');});
  console.log('TREATMENT_REVIEW_HARNESS: '+JSON.stringify(tests));const failures=tests.filter(test=>!test.pass);if(failures.length)throw new Error('Treatment review harness gagal: '+failures.map(test=>test.id).join(', '));return tests;
}
